import styled from '@emotion/styled'
import Card from '@src/components/profile/Card'
import BottomNavbar from '@src/components/shared/navbar/Bottom'
import { Container } from '@src/components/shared/Container'
import { DesktopOnly, MobileOnly } from '@src/components/shared/MediaQuery'
import TopNavbar from '@src/components/shared/navbar/Top'
import { media } from '@src/styles/media'
import { theme } from '@src/styles/theme'
import Head from 'next/head'
import Tabs from '@src/components/profile/Tabs'
import MeetNewMembers from '@src/components/shared/MeetNewMembers'
import RelatedProfiles from '@src/components/shared/RelatedProfiles'

const Base = styled.div`
  background-color: ${({ theme }) => theme.color.bodyBackground};
`

const Wrapper = styled(Container)`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  ${media.tabletLandscape} {
    padding: 0 3rem;
  }
`

const Content = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  width: 100%;

  ${media.tabletLandscape} {
    align-items: baseline;
    padding: 0 2rem 0.75rem 2rem;
  }
`

const Columns = styled.div`
  display: flex;
  flex-direction: row;
  gap: 16px;
`

const Row = styled.div`
  display: flex;
  flex-direction: column;
  gap: 16px;
`

export default function Page() {
  return (
    <Base>
      <TopNavbar withBackIcon text="Profile" />
      <BottomNavbar />
      <MobileOnly>
        <Card />
        <Tabs />
      </MobileOnly>
      <Wrapper>
        <Content>
          <Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <DesktopOnly>
            <Card />
            <Columns>
              <Tabs />
              <Row>
                <MeetNewMembers />
                <RelatedProfiles />
              </Row>
            </Columns>
          </DesktopOnly>
        </Content>
      </Wrapper>
    </Base>
  );
}

Page.theme = theme
